apiVersion: apps/v1
kind: Deployment
metadata:
  name: aes-sample-portal
  namespace: default
  labels:
    app: aes-portal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aes-portal-deployment
  template:
    metadata:
      labels:
        app: aes-portal-deployment
    spec:
      serviceAccountName: aes-sample-portal
      containers:
      - image: abcdzz1.azurecr.io/private/sample_app:main_14729997383
        imagePullPolicy: Always
        name: aes-sample-portal
        envFrom:
          - configMapRef: {name: aes-portal-config}
        command: ["flask"]
        args: ["--app", "boiler_portal", "run", "--host", "0.0.0.0"]
