apiVersion: apps/v1
kind: Deployment
metadata:
  name: aes-sample-iot-device
  namespace: azure-iot-operations
  labels:
    app: aes-sample-iot-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aes-sample-iot-device
  template:
    metadata:
      labels:
        app: aes-sample-iot-device
    spec:
      serviceAccountName: aes-sample-iot-device
      containers:
      - image: abcdzz1.azurecr.io/private/sample_app:main_14729997383
        imagePullPolicy: Always
        name: aes-sample-iot-device
        command: ["python3"]
        args: ["-m", "boiler_simulator", "-s", "aio-broker", "-p", "18885", "-c", "/var/run/certs/ca.crt"]
        volumeMounts:
        - name: trust-bundle
          mountPath: /var/run/certs
      volumes:
      - name: trust-bundle
        configMap:
          name: azure-iot-operations-aio-ca-trust-bundle # Default root CA cert

