name: Update image version on main branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: string
      registry:
        description: 'Registry'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  update-img:
    runs-on: ubuntu-latest
    steps:
      - name: Print the image version
        run: echo The version is ${{ inputs.tag }}
        
      - uses: actions/checkout@v4

      - name: Push to branch
        run: | 
          ./scripts/push_to_branch.sh ${{ inputs.registry }} ${{inputs.branch}} ${{ inputs.tag }}


          
