name: Update image version on main branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: string
      registry:
        description: 'Registry'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  update-img:
    runs-on: ubuntu-latest
    steps:
      - name: Print the image version
        run: echo  The version is ${{ inputs.tag }}
        
      - uses: actions/checkout@v4

      - name: Push to branch
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git branch ${{ inputs.branch }}
          git checkout ${{ inputs.branch }}
          ./scripts/build.sh -r ${{ inputs.registry }} -t ${{ inputs.tag }}
          git add ./deploy/*
          git commit -m "Update image ${{ inputs.tag }}"
          git push --set-upstream origin ${{ inputs.branch }}
