on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  update-img:
    runs-on: ubuntu-latest
    steps:
      - name: Print the image version
        run: echo  The version is ${{ inputs.tag }}
        
      - uses: actions/checkout@v4

      - name: Push to branch
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git branch action/${{ inputs.tag }}
          git checkout action/${{ inputs.tag }}
          ./scripts/build.sh -r ${{ inputs.registry }} -t ${{ inputs.tag }}
          git add ./deploy/*
          git commit -m "Update image ${{ inputs.tag }}"
          git push --set-upstream origin action/${{ inputs.tag }}

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          gh pr create --base main --head action/${{ inputs.tag }} --title "Update image ${{ inputs.tag }}" --body "This PR updates the image to version ${{ inputs.tag }}."

          
